-- Script para poblar la base de datos

-- Insertar Categorias
INSERT INTO Categorias (id, nombre) VALUES (1, 'CLASICO');
INSERT INTO Categorias (id, nombre) VALUES (2, 'EXPANSION ');

-- Insertar Subcategorias
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('PAÍSES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('CIUDADES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('COMIDAS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('NOMBRES DE VARON', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('NOMBRES DE MUJER', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('"ALIMENTOS (Platos', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('ANIMALES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('COLORES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('OBJETOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('VERBOS EN INFINITIVO', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('CALLES Y AVENIDAS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN EL BAÚL DE LA ABUELA', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN LA CARTERA DE LA DAMA', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('CUERPO HUMANO', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('PROFESIONES Y OFICIOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('"FAMOSOS DEL ESPECTÁCULO (Nombre', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('"PERSONAJES HISTÓRICOS (Nombre', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('"ARTISTAS (Nombre', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('SUSTANTIVOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('CLUBES DE FUTBOL', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RIOS Y MARES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('BANDAS O CANTANTES (Ej: The Rolling Stones va por la “r” o la “s”)', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('"ESCRITORES Y POETAS (Nombre', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('MARCAS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('DEPORTES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('FRUTAS O VERDURAS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('INSTRUMENTOS MUSICALES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('PELÍCULAS O SERIES (Ej: “El paciente ingles” aplica para la “p”)', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('ACTORES Y ACTRICES (Aplica solo una vez. Ej: Robbie Williams va en la “r” o en la “w”)', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('ADJETIVOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS (O MARCAS) DE ALIMENTOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS (O MARCAS) DE INDUMENTARIA', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS MULTINACIONALES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS DE SERVICIOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS DE TECNOLOGIA', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS DE AEROLÍNEAS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS AUTOMOTRICES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS DE UNA PALABRA DE DOS SÍLABAS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS DE UNAPALABRADE TRES SÍLABAS O MÁS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS ARGENTINAS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A BEBÉS O NIÑOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A LOS ABUELOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A LOS ABOGADOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A LOS MÉDICOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A LOS VIAJES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A LOS ESTUDIANTES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A LA COCINA', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A LAS VACACIONES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A LOS DEPORTISTAS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A LA OFICINA', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('SUPERHÉROES', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('CAPITALES DEL MUNDO', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('ELEMENTOS QUÍMICOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('BEBIDAS O TRAGOS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A ÁFRICA', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO A ASIA', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RELATIVO AL ESPACIO', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('ÁRBOLES O PLANTAS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RAZAS DE PERROS', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('MEDIOS DE TRANSPORTE', 1);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('HISTORIA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('GEOGRAFÍA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('PERSONAS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('DEPORTISTAS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('MUSICA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('COMODIN', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('BARRIOS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('PORTEÑOS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('POLITICOS PRÓCERES', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('CLUBES', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('FUTBOL ', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('AUTOMOVILISMO', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('TENIS - PALETA - PADDLE  -PING PONG', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('BASQUET - VOLEY', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('JUEGOS OLIMPICOS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('CAMPEONES', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EXTREMOS - DE CONTACTO O AVENTURA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('ARGENTINA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('ATLETISMO - GIMNASIA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('COMODIN', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('INVENTOS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('OBJETOS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('APLICACIONES', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('JUEGOS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN MI COMPUTADORA HAY', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('CON MI SMARTPHONE PUEDO', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN EL FUTURO VA A EXISTIR', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('SOFTWARE', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('COMODIN', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN LA PLAYA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN LA CASA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN LA CALLE', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN LA MONTAÑA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN LA CIUDAD', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN EL SHOPPING', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN LA OFICINA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN EL COLEGIO', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN EL CAMPO', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('COMODIN', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN LA FERRETERIA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN EL FREE SHOP', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN EL KIOSCO', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN EL RESTORAN', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN LA LIBRERIA O ARTISTICA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN EL BAR', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN LA ESTACION DE SERVICIO', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN LA FARMACIA', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN EL HIPERMERCADO', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('COMODIN', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('NOMBRE DE MUJER O VARON', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('ANIMALES - FRUTAS O VERDURAS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EMPRESAS O MARCAS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('RIOS - MARES - OCEANOS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('PAISES - CAPITALES - CIUDADES - LOCALIDADES', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('INSTRUMENTOS - HERRAMIENTAS', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('MUSICA - TEATRO -CINE - TV', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('EN MI PAIS HAY', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('APELLIDOS DEL MUNDO', 2);
INSERT INTO Subcategorias (nombre, categoria_id) VALUES ('COLORES - LUGARES - CALLES - AVENIDAS', 2);
